# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa585b713ce5648a52118cbe9f083e2df4378b46d7b745dfa3e841c952d4418002eb9922dff2b7d8817666f0e1d428d42207775f13337a34d72b351e5edeb912

test:
  secret_key_base: b6c3b5f6ae44651780561a378f25604274c9c1f066dfa826b46774007d25b7475ca75fead40581aa47b04082e405f0fb155212f31a7687fbe7c8125b1f0f042c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
